---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

library(readxl)
activity <- read_excel("Coursera/repdata%2Fdata%2Factivity/activity.csv")
View(activity)

## What is mean total number of steps taken per day?

stepsbyday <- aggregate(steps~date,rm.na=TRUE,data=activity,FUN=sum)
aggregate(steps ~ date, data = activity, FUN = mean)
aggregate(steps ~ date, data = activity, FUN = median)

mean=10766.19, median=10765.

## What is the average daily activity pattern?

plot(aggregate(steps ~ interval, data = activity, FUN = mean), type = "l")
max(activity$steps, na.rm = TRUE)
sum(is.na(activity))

## Imputing missing values

activity2 <- activity
sapply(activity2, class)
activity2$steps[is.na(activity2$steps)] <- mean(na.omit(activity$steps))
activity2$date <- as.Date(activity2$date, format = "%Y-%m-%d")
stepsbyday2 <- aggregate(steps ~ date, rm.na = TRUE, data = activity2, FUN = sum)
par(mfrow = c(1, 2))
plot(stepsbyday2, type = "h", lwd = 5, lend = "square", main = "No NA")
abline(h = seq(0, 20000, 2500), lty = "dashed")
aggregate(steps ~ date, data = activity2, FUN = mean)
aggregate(steps ~ date, data = activity2, FUN = median)


## Are there differences in activity patterns between weekdays and weekends?

activity2$weekday <- factor(format(activity2$date, "%A"))
levels(activity2$weekday) <- list(weekday = c("Monday", "Tuesday",
                                              "Wednesday", "Thursday",
                                              "Friday"), weekend =
                                          c("Saturday", "Sunday"))
xyplot(steps ~ interval, data=activity2$weekday, 
groups=activity2$weekday, type="l", grid=T)
